spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

travel:
  request:
    queue:
      name: travel-expenses-request-queue
  response:
    queue:
      name: travel-expenses-response-queue

server:
    port: 8081